* On Friendship

Types of Friends, Where to find them, Rules for Engagement, How to make them.

[1] http://homepages.ius.edu/.../html/notes/Chapter22/BFS.htm
[2] https://en.wikipedia.org/wiki/PageRank#Damping_factor

** Types of Friends

I am not sure I presently have the patience (or can see why it would
be productive) to exhaustively classify types of friends. I'll list a
few important ones. Suffice to say, different types of friends entail
different levels of commitment, attachment, trust, and benefits.

*** Dampers
I try to find friends who are "dampers". Damping factors. Some of the
important people I associate with are like damping factors (see
explanation as it pertains to PageRank algorithm) [1]. Dampers are
good at inhibiting unwanted behaviour in networks, like infinite
cycles. In PageRank's case, they introduce stochasticism via a random
restart. I assert "dampers" contribute similarly to your life (as if
we really need more stochasticism!). I choose these types of friends
because I fundamentally respect them and their abilities and thus know
I will enjoy their company even in different (read: strange)
scenarios, even if I would not otherwise enjoy the type of event they
encourage me to participate in. This is also a good way to explore
edges along your friends graph and meet new people.

*** Partners
One thing I have learned is, to be successful at hitting goals, you
need to also be successful at effective (yes, there is such a thing)
procrastination (i.e. unwinding). It's in these types of healthy,
unwinding activities I often find meaningful friendships.

“You are the average of the five people you spend the most time with.”
― Jim Rohn

"Arnold Schwarzenegger might be the most influential bodybuilders of
all times and also an accomplished powerlifter with his 710lb
Deadlift, but he didn’t get there alone. Arnold had a key long-term
training partner: powerlifting champion Franco Columbo – 655lb
Squatter, 750lb Deadlifter and later 3x Mr Olympia."
http://stronglifts.com/arnold-schwarzenegger-franco-columbo-training-partners/


** Locating Friends
Friendships grow and because of this, they have to grow
from/on/through something. This something can be a place, an idea, an
activity, an emotional need, etc.

Abstractly, here are some guiding principles I use to find interesting people:
1) Love work, then meet with people at work to learn from
2) Find friends through activities (successful/healthy procrastination; e,g: gym, reading group, game night, hikes, music, art)
3) Through academic learning (perhaps through work, or arrange activities with people you discover wish to learn similar things)
4) Through "dampers" (see below; people you already trust who act as a trusted filter for exposing you to new things/people)

Here are the places / activities where I find myself meeting people:
1) Noisebridge Hackerspace
2) Rock Climbing @ Mission Cliffs Indoor Rock Climbing Gym
3) Five Minutes of Shame (Hackerquarters bi-monthly event)
4) Mentors @ coffee shops. (stanza, fourbarrel, sightglass, cafe centro)
5) The MoMa (which is now defunct)
7) Mellow Beats & Board Games
8) Damping Factors (see above: Types of Friends)

** Rules for Engagement

Be genuine. People worth being friends with deserve friends they can
trust. Let people know what your expectations are, what type of
friendship you're looking for. Be honest about your passions. It's
much easier finding friends when you love your work; i.e. work is not
work but life itself. Most of the people I meet with for coffee during
work hours are extremely inspiring as they are solving problems I so
deeply care about (it's an incredible vicarious feeling) -- each one
in some way teaches me something insightful and I have come to view
these people as some degree of mentors.


** How to Make Friends

*** Strategies & Heuristics
Life is short and we become more like those we spend out time with,
thus I treat the process seriously and filter my friends. Perhaps some
may call this being too risk adverse. I actually think it's the
opposite: it's similar to a comparison of a depth first (this
strategy; filtering friends) versus breadth first search (being
friends with anyone no filter). DFS is provably incomplete and is thus
in some abstract sense riskier. Granted my actual search is more
heuristic graph search than DFS, the point stands that BFS traversal
has desirable properties, albeit potentially diabilitating
consequences. There's nothing wrong with employing a different
strategy. Put some thought into understand the advantages and
disadvantages of each and have mechanisms for mitigating worst-case
scenarios (becoming overwhelmed with friends, stale relationships,
etc).

I tend to prefer and prioritize deep friendships because I find it
difficult to context switch between many people, trust people whom I
don't understand well or haven't invested significant time in, I don't
typically enjoy people and their interests (they require a lot of
energy and are exhausting -- I am an introvert), and I want to benefit
from compound interest (obtaining mutual context) over time. As a
result, I tend to have many more acquaintances than friends.

That being said, my definition of friendship has drastically changed
over the last few months. I've been reaching out to people who have
similar goals and passions, have been having some truly rewarding
conversations, and great recommendations + resources.

    From https://www.facebook.com/michael.karpeles/posts/10102182038234750

    A new thing I'm doing:

    Talk to a different researcher/professor of Knowledge
    Representation & NLP AI/ML every month. Today was Eamon Duede,
    executive of the knowledge lab @ University of Chicago.  Eamon
    helped me discover MIT Lab's Pantheon project[1] which is very
    similar to my (rather Mike Bostock's) zoomable tree-graph of the
    math/MSC2010 taxonomy[2]. Supposedly MIT + Chicago are working
    together on the same curricula/dependency generation as I am via
    Wikipedia! i.e. building a tree of dependencies for
    learning/understanding any given Wikipedia page. Might as well
    help them out!‪#uniting the field and making it feel smaller,
    slowly but surely.

    [1] http://pantheon.media.mit.edu/…/HU/…/-4000/2010/H15/pantheon
    [2] https://math.mx

*** Start With Your Peculiarities
It's important to understand your own pecuiliaries. I have a
peculiarity which may not resonant with most people. While, especially
around those with whom I am comfortable, I many not have the most
serious/mature demeanor in interactions (I'm a closet troll of
Socratic proportion, painfully sarcastic, and perpetually supressing
the imp of the perverse), my view of life and my "purpose" is
dreadfully serious. When it is proposed that an issue I view as a
moral imperative is to be addressed with laissez faire, I feel
obligated to act.

**** Life of Purpose
It's not very humble of me to say, but I'd like to think I try to be
something of a citizen of the world (maybe not a great one). I see
there as being things the world needs, human rights the world deserves
(like Universal Access to Knowledge) and sometimes I am struck by
intense depression because I don't feel I have the right to be happy
until others have the same access to organized information as someone
as privileged as myself. There are people who can't accomplish their
live goals, not because of their abilities, but because of their
consequence of their birth. And that burden, that reality, is
something I can't bare to ignore. It really hurts.

It is difficult to find people who genuinely respect and appreciate
these sentiments -- and who wants to be around someone who doesn't
respect who you are? I psychologically have a hard time escaping a
"work" mindset because I don't view work as work. To me, there's just
"life". Problems which are worth solving.  I live a fairly intentional
life which I aspire to craft around learning and applying knowledge. I
often slip and am ineffective at this goal, but nonetheless I am
hypocritically dogmatic and resolute; to my fault, I am impatient with
people who don't have similar views of the seriousness of life and the
imperativeness of our actions.

**** Dislikes: Trivia & Media
I am human, I am wired to enjoy trivia and media. I don't like that I
enjoy trivia and media. I prefer other methods of productive
procrastination. Many people I know optimize more for enjoying life
than accountability. After years of mistakingly viewing such things as
binary (rather than spectrums), I now have a greater appreciation of
the role of balance and try to be more accommodating on this front.

**** Towards Improvement: Objectivity, Criticism, Accountability

I want my friendships to push me, to keep me accountable, to help me
grow and mature, be more accountable and informed. To make me more
thoughtful, to question me, to make me more honest, more humble (this
last one sure is low hanging fruit...)

**** Connecting the dots

These peculiarites can be my greatest flaws. One of my life goals is
to blur the lines of things. To realize classifications as the
spectrums they and not an over-simplified yes or no. To eliminate the
arbitrary borders, for example, of computer documents and to instead
think in terms of the ideal mashup of the content we want accross
different documents. Yet, my philosophy is such that there are
dividing lines everywhere; my peculiarities are these lines. And yet I
am not sure I am mature or disciplined enough to compromise these
ideals, unless a person shows me how wonderful these qualities are
that I am forced to make an exception. Coincidentally, these are often
my favourite people. Alan Davis, Tom Hamill, Mark Neyer, Stephen
Balaban, Akhil Aryan, and Jessy Exum are a few of these people. I
imagine Drew Winget would make this list for most people, except
usually his contributions re-enforce and empower my ideas rather than
suggest alternate paradigms. You need that too -- these people, as an
analogy, are your spotters in the weight room. They amplify your
efforts.
